# NOTE: The package version does not correspond to an upstream version but
#       rather denotes the commit number. E.g., "0.0.35" is the 35th commit.
{% set version = "0.0.44" %}
{% set commit = "ceb292363ec84358c9a276ef23aa0de893e59b84" %}

package:
  name: go-licenses
  version: {{ version }}

source:
  - url: https://github.com/google/go-licenses/archive/{{ commit }}.tar.gz
    sha256: 12e90501e8fd009d60dbc1447330d14329d9cbbd71f24e0dcf4996a9d80b0c80
    patches:
      - 0001-Recognize-unlicense-file-name-patterns.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - posix  # [win]
  host:
  run:
    - go

test:
  commands:
    - git clone --depth=1 "https://github.com/google/go-licenses"
    - cd go-licenses
    - go-licenses csv . | findstr "Apache-2.0 BSD-.-Clause MIT"             # [win]
    - go-licenses csv . | grep 'Apache-2\.0\|BSD-.-Clause\|MIT\|Unlicense'  # [not win]
  requires:
    - git
    - go

about:
  home: https://github.com/google/go-licenses
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: 'A tool to collect licenses from the dependency tree of a Go package in order to comply with redistribution terms.'

extra:
  recipe-maintainers:
    - dhirschfeld
    - mbargull
