{% set version = "1.2.0" %}

package:
  name: go-licenses
  version: {{ version }}

source:
  - url: https://github.com/google/go-licenses/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3b8dfaeaa31cf4b5e5f55624a6d37a851ab40daf7c96c9bf25ad0489def30ba4
    patches:
      - 0001-Recognize-unlicense-file-name-patterns.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - posix  # [win]
  host:
  run:
    - go

test:
  commands:
    - git clone --depth=1 "https://github.com/google/go-licenses"
    - cd go-licenses
    - go-licenses csv . | findstr "Apache-2.0 BSD-.-Clause MIT"             # [win]
    - go-licenses csv . | grep 'Apache-2\.0\|BSD-.-Clause\|MIT\|Unlicense'  # [not win]
  requires:
    - git
    - go

about:
  home: https://github.com/google/go-licenses
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: A tool to collect licenses from the dependency tree of a Go package in order to comply with redistribution terms.

extra:
  recipe-maintainers:
    - dhirschfeld
    - mbargull
    - bollwyvl
